/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRegistrarVotoRouteImport } from './routes/_app/registrar-voto'
import { Route as AppProyectosRouteImport } from './routes/_app/proyectos'
import { Route as AppInicioRouteImport } from './routes/_app/inicio'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegistrarVotoRoute = AppRegistrarVotoRouteImport.update({
  id: '/registrar-voto',
  path: '/registrar-voto',
  getParentRoute: () => AppRoute,
} as any)
const AppProyectosRoute = AppProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/inicio': typeof AppInicioRoute
  '/proyectos': typeof AppProyectosRoute
  '/registrar-voto': typeof AppRegistrarVotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/inicio': typeof AppInicioRoute
  '/proyectos': typeof AppProyectosRoute
  '/registrar-voto': typeof AppRegistrarVotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/proyectos': typeof AppProyectosRoute
  '/_app/registrar-voto': typeof AppRegistrarVotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/inicio' | '/proyectos' | '/registrar-voto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/inicio' | '/proyectos' | '/registrar-voto'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/inicio'
    | '/_app/proyectos'
    | '/_app/registrar-voto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/registrar-voto': {
      id: '/_app/registrar-voto'
      path: '/registrar-voto'
      fullPath: '/registrar-voto'
      preLoaderRoute: typeof AppRegistrarVotoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proyectos': {
      id: '/_app/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof AppProyectosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInicioRoute: typeof AppInicioRoute
  AppProyectosRoute: typeof AppProyectosRoute
  AppRegistrarVotoRoute: typeof AppRegistrarVotoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInicioRoute: AppInicioRoute,
  AppProyectosRoute: AppProyectosRoute,
  AppRegistrarVotoRoute: AppRegistrarVotoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
